---
# tasks file for apache2
- name: install web componets
  apt: name={{item}} state=present
  with_items:
    - apache2
    - libapache2-mod-wsgi

- name: ensure mod_wsgi is enabled
  apache2_module: state=present name=wsgi
  notify: restart apache2

- name: deactive default apache2 sites-available
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
  notify: restart apache2

- name: ensure apache2 is started
  service: name=apache2 state=started enabled=yes
